name: ygking_design_ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  url_launcher: ^6.1.14
  universal_html: ^2.2.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/
  #   - assets/images/
  #   - assets/fonts/
    
  # fonts:
  #   - family: YGking
  #     fonts:
  #       - asset: assets/fonts/YGking-Regular.ttf
